apiVersion: v1
kind: Namespace
metadata:
  name: prj-tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prj-tomcat
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: public.ecr.aws/a6y9d2q4/tomcat:v1.0
        resources:
          requests:
            cpu: "30m"
          limits:
            cpu: "50m"
        ports:
        - containerPort: 8080
          name: tomcat-port
        env:
        - name: MYSQL_HOST
          value: lgd-rds-mariadb.cx0eusekucl1.ap-northeast-2.rds.amazonaws.com
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: usersdb
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: "5495821254"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prj-tomcat
  name: tomcat-service
spec:
  type: ClusterIP
  selector:
    app: tomcat
  ports:
  - port: 8080
    targetPort: 8080
    name: tomcat-port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prj-tomcat
  name: tomcat-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat-deployment
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50